### ISSUE TITLE
GIF合成会出现颜色偏差 GIF synthesis will appear color deviation

### ISSUE THREAD

**Issue by kafu0611** [leoding86/pixiv-ugoira-managa-downloader#1]
使用GIF合成功能可能会出现颜色偏差导致合成出现的图片与原图不符
例：
原图：https://www.pixiv.net/member_illust.php?mode=medium&illust_id=69193634
使用合成功能之后导出的GIF：https://i.imgur.com/fGfqDeL.gifv

**Comment by leoding86** [comment]
这个是因为gifjs采样的方式反应出来的色差，通俗讲你提供的例子图片看似图片颜色没有多少，起始包含了很多颜色，通过调整质量参数可以还原色彩。目前扩展没有提供质量调整的设置，后期会加入。

已经更新到1.5.1，加入动图质量设定。
